# Generated by Django 4.0.4 on 2022-11-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
