# Generated by Django 4.0.4 on 2022-11-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
