# Generated by Django 4.0.4 on 2022-11-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_content_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='contnet',
            new_name='content',
        ),
    ]
