# Generated by Django 4.0.4 on 2022-12-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_image',
            field=models.ImageField(blank=True, default='../static/images/panji-adhi-YLtJv5rCFFM-unsplash.jpg', upload_to=''),
        ),
    ]
